baseurl = "https://example.org/"
languageCode = "en-us"
title = "DmytryKo's site"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
# disqusShortname = "spf13"
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"


[params]
    site_author = "Dmytro Kozachok"
    site_description = "The awesome site of Dmytro Kozachok."
    location = "Kyiv, Ukraine"
    # Link custom assets relative to /static
    avatar = "img/me2.png"
    header_background = "img/desk.jpg"
    header_title = "My website"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Define which content types are shown on the homepage
    mainSections = ["post"]

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = ""
    facebook  = ""
    linkedin  = "dima0685"
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "Dmytro-Kozachok"
    gplus     = ""
